CREATE SEQUENCE mbot.USUARIO_SEQ
        INCREMENT BY 1
        MINVALUE 1
        START WITH 1;

CREATE SEQUENCE mbot.MENSAGEM_SEQ
        INCREMENT BY 1
        MINVALUE 1
        START WITH 1;

CREATE SEQUENCE mbot.CANAL_SEQ
        INCREMENT BY 1
        MINVALUE 1
        START WITH 1;

CREATE SEQUENCE mbot.LEMBRETE_SEQ
        INCREMENT BY 1
        MINVALUE 1
        START WITH 1;

CREATE TABLE mbot.USUARIO
(
    ID             BIGINT DEFAULT nextval('mbot.USUARIO_SEQ') NOT NULL,
    DT_CADASTRO   TIMESTAMP         NOT NULL,
    NOME            VARCHAR(255)    PRIMARY KEY  NOT NULL
);

CREATE TABLE mbot.CANAL
(
    ID             BIGINT DEFAULT nextval('mbot.CANAL_SEQ') NOT NULL,
    DT_CADASTRO   TIMESTAMP         NOT NULL,
    NOME            VARCHAR(255)   PRIMARY KEY  NOT NULL
);


CREATE TABLE mbot.LEMBRETE
(
    ID             BIGINT DEFAULT nextval('mbot.LEMBRETE_SEQ') PRIMARY KEY NOT NULL,
    DT_CRIACAO   TIMESTAMP         NOT NULL,
    CONTEUDO            VARCHAR(600)   NOT NULL,
    DESTINATARIO   VARCHAR(255) NOT NULL,
    REMETENTE      VARCHAR(255) NOT NULL,
    CONSTRAINT DEST_LEMBRETE FOREIGN KEY (DESTINATARIO) REFERENCES mbot.USUARIO (NOME),
    CONSTRAINT REMET_LEMBRETE FOREIGN KEY (REMETENTE) REFERENCES mbot.USUARIO (NOME)
);


CREATE TABLE mbot.MENSAGEM
(
    ID             BIGINT DEFAULT nextval('mbot.MENSAGEM_SEQ') PRIMARY KEY NOT NULL,
    DT_ENVIO   TIMESTAMP         NOT NULL,
    CONTEUDO            VARCHAR(600)      NOT NULL,
    NOME_USUARIO VARCHAR(255) NOT NULL,
    NOME_CANAL VARCHAR(255) NOT NULL,
    CONSTRAINT MENSAGEM_USUARIO FOREIGN KEY (NOME_USUARIO) REFERENCES mbot.USUARIO (NOME),
    CONSTRAINT MENSAGEM_CANAL FOREIGN KEY (NOME_CANAL) REFERENCES mbot.CANAL (NOME)
);

INSERT INTO mbot.CANAL (DT_CADASTRO, NOME) VALUES (current_timestamp, 'magicbot321');

INSERT INTO mbot.CANAL (DT_CADASTRO, NOME) VALUES (current_timestamp, 'haxk');

INSERT INTO mbot.CANAL (DT_CADASTRO, NOME) VALUES (current_timestamp, 'rosethemagician');

INSERT INTO mbot.CANAL (DT_CADASTRO, NOME) VALUES (current_timestamp, 'fabzeef');

INSERT INTO mbot.CANAL (DT_CADASTRO, NOME) VALUES (current_timestamp, 'zahra');

INSERT INTO mbot.CANAL (DT_CADASTRO, NOME) VALUES (current_timestamp, 'forsen');
